import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

const readinessPath = 'docs/v1.1-integration-readiness.md';

describe('v1.1 integration readiness notes', () => {
  it('documents the release-candidate command matrix and verification gates', async () => {
    const content = await readFile(readinessPath, 'utf8');

    for (const expected of [
      '# v1.1 Integration Readiness',
      'AGENTSCOPE_FIXTURES_MODE=1',
      'agentscope search proxy --json',
      'agentscope show child-019d --json',
      'agentscope export child-019d --out <directory>',
      'agentscope doctor --json',
      'manifest.json',
      'npm test',
      'npm run build',
      'observed behavior, not a stable public API',
      'conservative',
      'tool-output/',
    ]) {
      expect(content).toContain(expected);
    }

    for (const requirement of [
      'REQ-001',
      'REQ-002',
      'REQ-003',
      'REQ-004',
      'REQ-005',
      'REQ-006',
      'REQ-007',
      'REQ-008',
      'REQ-009',
      'REQ-010',
      'REQ-011',
    ]) {
      expect(content).toContain(requirement);
      expect(content.split(requirement)).toHaveLength(2);
    }
  });

  it('keeps readiness notes public-repo safe', async () => {
    const content = await readFile(readinessPath, 'utf8');
    const unsafePatterns = [
      /\/Users\//,
      /\/home\//,
      /\.planning\//,
      /\.superpowers\//,
      /\.pre-mvp\//,
      /sk-[A-Za-z0-9_-]{8,}/,
      /ghp_[A-Za-z0-9_]{8,}/,
      /xoxb-[A-Za-z0-9-]{8,}/,
      /-----BEGIN [A-Z ]+PRIVATE KEY-----/,
      /authorization\s*[:=]/i,
      /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i,
      /(?:generated by|co-authored-by|written by)\s+(?:ai|agent|claude|codex|opencode)/i,
    ];

    const findings = unsafePatterns.filter((pattern) => pattern.test(content));
    expect(findings, `${readinessPath} contains unsafe public-repo content`).toEqual([]);
  });
});
