import { describe, expect, it } from 'vitest';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

interface HygieneFinding {
  file: string;
  risk: string;
}

const fixtureRoot = 'fixtures';
const allowedFragments = ['/workspace/project', '/Users/synthetic', 'project-one', 'synthetic', 'AGENTSCOPE_FIXTURES_MODE'];

const unsafePatterns: Array<{ risk: string; pattern: RegExp }> = [
  { risk: 'real home path', pattern: /\/Users\/(?!synthetic\b)[^\s"']+/ },
  { risk: 'linux home path', pattern: /\/home\/[^\s"']+/ },
  { risk: 'windows home path', pattern: /C:\\Users\\[^\s"']+/i },
  { risk: 'local workflow directory .planning/', pattern: /\.planning\// },
  { risk: 'local workflow directory .superpowers/', pattern: /\.superpowers\// },
  { risk: 'local workflow directory .pre-mvp/', pattern: /\.pre-mvp\// },
  { risk: 'local runtime directory .claude/', pattern: /\.claude\// },
  { risk: 'local runtime directory .codex/', pattern: /\.codex\// },
  { risk: 'local runtime directory .config/opencode/', pattern: /\.config\/opencode\// },
  { risk: 'secret marker sk-', pattern: /sk-[A-Za-z0-9_-]{8,}/ },
  { risk: 'secret marker ghp_', pattern: /ghp_[A-Za-z0-9_]{8,}/ },
  { risk: 'secret marker xoxb-', pattern: /xoxb-[A-Za-z0-9-]{8,}/ },
  { risk: 'private key marker', pattern: /-----BEGIN [A-Z ]+PRIVATE KEY-----/ },
  { risk: 'api key marker', pattern: /api[_-]?key\s*[:=]/i },
  { risk: 'password marker', pattern: /password\s*[:=]/i },
  { risk: 'secret marker', pattern: /secret\s*[:=]/i },
  { risk: 'bearer credential', pattern: /bearer\s+[A-Za-z0-9._-]{8,}/i },
  { risk: 'authorization credential', pattern: /authorization\s*[:=]/i },
  { risk: 'email address', pattern: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i },
  { risk: 'AI or agent attribution', pattern: /(?:generated by|co-authored-by|written by)\s+(?:ai|agent|claude|codex|opencode)/i },
];

async function listFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listFiles(entryPath)));
    } else if (entry.isFile()) {
      files.push(entryPath);
    }
  }

  return files.sort();
}

function stripAllowedFragments(content: string): string {
  return allowedFragments.reduce((current, fragment) => current.split(fragment).join(''), content);
}

describe('fixture public-repo hygiene', () => {
  it('keeps committed fixtures free of private local data and attribution', async () => {
    const findings: HygieneFinding[] = [];

    for (const file of await listFiles(fixtureRoot)) {
      const content = stripAllowedFragments((await readFile(file)).toString('utf8'));
      for (const { risk, pattern } of unsafePatterns) {
        if (pattern.test(content)) {
          findings.push({ file, risk });
        }
      }
    }

    expect(findings, `public-repo hygiene findings: ${JSON.stringify(findings)}`).toEqual([]);
  });
});
